"""Generate `crates/hanglock-render/src/face_data.rs` from the reference face.

The face is authored once, in `hanglock_ref.py`, because that is where it could be *looked at*:
drawing a glyph at 96 px in a pure-Python renderer and viewing the result is a far faster loop than
building the Windows app to do it. This script quantises the same outlines into Rust constants, so
the shipped face is not a re-typed approximation of the reviewed one — it is that data.

    python3 tools/model/gen_face.py > crates/hanglock-render/src/face_data.rs
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hanglock_ref as h  # noqa: E402

Q = 5  # decimals; cap-relative units, so 1e-5 of a cap height

# The emitted text is checked in verbatim and then linted, so it has to satisfy the lints at the
# source: `clippy::doc_markdown` wants a capitalised product name inside backticks, and CI runs
# clippy with `-D warnings`. `tools/ci/currency.py source` compares *content*, not bytes, so the
# layout `cargo fmt` applies to the committed file (one item per line, a comma before each closing
# delimiter) is not drift — but the backticks are, because they are characters.


def pt(p):
    return "Pt { x: %.*f, y: %.*f }" % (Q, p[0], Q, p[1])


def main():
    print("// @generated by tools/model/gen_face.py — DO NOT EDIT.")
    print("// Edit the face in tools/model/hanglock_ref.py (FACE_GLYPHS) and re-run the generator.")
    print("//!")
    print("//! The Hanglock face: geometric, monoline, tabular by construction. Every glyph is a set")
    print("//! of *strokes* (polylines in a unit cap-height box, y down) rather than filled outlines,")
    print("//! because the painter already draws anti-aliased capsules for the cord — so type and cord")
    print("//! share one coverage function, one weight, one join style, and one cost model. No font")
    print("//! file, no rasteriser, and nothing here needs `ClearType` (see docs/decisions/0001, which")
    print("//! is a constraint on every transparent-window renderer, not on this one).")
    print()
    print("/// Extra advance per glyph, as a fraction of cap height. Together with the fixed")
    print("/// [`ADVANCE`] this is what makes the digits tabular: `1` and `8` occupy the same box, so")
    print("/// `11:11` and `10:42` cannot shift the run.")
    print("pub const ADVANCE: f32 = %.*f;" % (Q, h.ADV))
    print("/// Distance from the cap height to the stroke weight (half-width). The one number that")
    print("/// sets the face's weight; grayscale anti-aliasing on a transparent surface punishes thin")
    print("/// strokes, so this sits at a deliberately sturdy value.")
    print("pub const STROKE_RATIO: f32 = %.*f;" % (Q, h.STROKE))
    print("pub const TRACKING: f32 = %.*f;" % (Q, h.TRACKING))
    print()
    print("#[derive(Clone, Copy, Debug, PartialEq)]")
    print("pub struct Pt {")
    print("    pub x: f32,")
    print("    pub y: f32,")
    print("}")
    print()
    print("#[derive(Clone, Copy, Debug, PartialEq)]")
    print("pub struct Dot {")
    print("    pub x: f32,")
    print("    pub y: f32,")
    print("    pub r: f32,")
    print("}")
    print()
    print("#[derive(Clone, Copy, Debug, PartialEq)]")
    print("pub struct Glyph {")
    print("    pub lines: &'static [&'static [Pt]],")
    print("    pub dots: &'static [Dot],")
    print("}")
    print()

    statics, entries = [], []
    for i, ch in enumerate(sorted(h.FACE_GLYPHS)):
        lines, dots = h.glyph(ch)
        line_refs = []
        for j, ln in enumerate(lines):
            name = "G%d_%d" % (i, j)
            pts = ", ".join(pt(p) for p in ln)
            statics.append("static %s: [Pt; %d] = [%s];" % (name, len(ln), pts))
            line_refs.append("&%s" % name)
        dot_src = ", ".join("Dot { x: %.*f, y: %.*f, r: %.*f }" % (Q, a, Q, b, Q, r) for a, b, r in dots)
        statics.append("static D%d: [Dot; %d] = [%s];" % (i, len(dots), dot_src))
        entries.append('    (%r, Glyph { lines: &[%s], dots: &D%d }),'
                       % (ch, ", ".join(line_refs), i))

    print("\n".join(statics))
    print()
    print("/// The glyph table. Linear search: 19 entries, looked up once per digit per frame, and a")
    print("/// map would be a dependency on ordering we do not have.")
    print("pub static GLYPHS: [(char, Glyph); %d] = [" % len(entries))
    print("\n".join(entries))
    print("];")
    print()
    print("#[must_use]")
    print("pub fn glyph(ch: char) -> Option<Glyph> {")
    print("    GLYPHS.iter().find(|(c, _)| *c == ch).map(|(_, g)| *g)")
    print("}")


if __name__ == "__main__":
    main()
