//! Hand-written Win32 declarations.
//!
//! This is the whole `unsafe` surface of Hanglock, and it is deliberately narrow: about forty
//! imports and a dozen structures, all of them stable since Windows 7. It is written by hand rather
//! than generated by the `windows` crate for one reason only — this build environment has no
//! crates.io access (`docs/decisions/0002-zero-dependencies.md`) — and adopting the generated
//! bindings later is a contained swap inside this crate.
//!
//! Two rules make hand-writing survivable:
//!
//! *   **Every layout is asserted at compile time.** `size_of` checks below turn a mistyped field
//!     into a build failure instead of memory corruption at runtime. Adding a field without the
//!     matching assertion is the one way this file can go quietly wrong, so the asserts sit next to
//!     the types they describe.
//! *   **Anything newer than the floor is loaded dynamically.** `SetProcessDpiAwarenessContext`
//!     and `GetDpiForWindow` do not exist on every supported Windows 10 build; a static import of
//!     them would make the executable fail to *start* there. Through `GetProcAddress` a missing
//!     export is a value the caller can test.

#![allow(dead_code, non_camel_case_types, non_snake_case, clippy::upper_case_acronyms)]

use std::ffi::c_void;
use std::mem::size_of;

pub type HWND = *mut c_void;
pub type HDC = *mut c_void;
pub type HBITMAP = *mut c_void;
pub type HICON = *mut c_void;
pub type HBRUSH = *mut c_void;
pub type HCURSOR = *mut c_void;
pub type HMENU = *mut c_void;
pub type HMODULE = *mut c_void;
pub type HANDLE = *mut c_void;
pub type HFONT = *mut c_void;
pub type WPARAM = usize;
pub type LPARAM = isize;
pub type LRESULT = isize;
pub type UINT = u32;
pub type UINT_PTR = usize;
pub type DWORD = u32;
pub type BOOL = i32;
pub type LONG = i32;
pub type ULONG = u32;
pub type WORD = u16;
pub type BYTE = u8;
pub type WCHAR = u16;
/// The `GWLP_*` and `SWP_*` argument slots are pointer-sized on x64 and 32-bit on x86; `isize`
/// matches both, which is why every declaration below uses it rather than `LONG`.
pub type LONG_PTR = isize;
pub type DWORD_PTR = usize;
pub type FN_WNDPROC = unsafe extern "system" fn(HWND, UINT, WPARAM, LPARAM) -> LRESULT;

// ---------------------------------------------------------------------------------------------
// window styles and messages
// ---------------------------------------------------------------------------------------------
pub const WS_POPUP: DWORD = 0x8000_0000;
pub const WS_VISIBLE: DWORD = 0x1000_0000;
pub const WS_EX_LAYERED: DWORD = 0x0008_0000;
pub const WS_EX_TOPMOST: DWORD = 0x0000_0008;
pub const WS_EX_TOOLWINDOW: DWORD = 0x0000_0080;
pub const WS_EX_NOACTIVATE: DWORD = 0x0800_0000;

pub const WM_NULL: UINT = 0x0000;
pub const WM_CREATE: UINT = 0x0001;
pub const WM_DESTROY: UINT = 0x0002;
pub const WM_SIZE: UINT = 0x0005;
pub const WM_ACTIVATE: UINT = 0x0006;
pub const WM_SETFOCUS: UINT = 0x0007;
pub const WM_NCHITTEST: UINT = 0x0084;
pub const WM_SETCURSOR: UINT = 0x0020;
pub const WM_MOUSEMOVE: UINT = 0x0200;
pub const WM_LBUTTONDOWN: UINT = 0x0201;
pub const WM_LBUTTONUP: UINT = 0x0202;
pub const WM_RBUTTONUP: UINT = 0x0205;
pub const WM_MBUTTONDOWN: UINT = 0x0207;
pub const WM_MOUSEWHEEL: UINT = 0x020A;
pub const WM_MOUSEHWHEEL: UINT = 0x020E;
pub const WM_LBUTTONDBLCLK: UINT = 0x0203;
pub const WM_KEYDOWN: UINT = 0x0100;
pub const WM_TIMER: UINT = 0x0113;
pub const WM_PAINT: UINT = 0x0009;
pub const WM_DISPLAYCHANGE: UINT = 0x007E;
pub const WM_SETTINGCHANGE: UINT = 0x001A;
pub const WM_DPICHANGED: UINT = 0x02E0;
pub const WM_POWERBROADCAST: UINT = 0x0218;
pub const WM_GETMINMAXINFO: UINT = 0x0024;
pub const WM_NCLBUTTONDOWN: UINT = 0x00A1;
pub const WM_ENTERSIZEMOVE: UINT = 0x0231;
pub const WM_EXITSIZEMOVE: UINT = 0x0232;
pub const WM_USER: UINT = 0x0400;
/// Tray notifications and the deferred-command pump. `WM_APP` ids are private to the process.
pub const WM_TRAYICON: UINT = WM_USER + 1;
pub const WM_APP_COMMAND: UINT = WM_USER + 2;
pub const WM_APP_TICK: UINT = WM_USER + 3;

pub const HTCLIENT: LRESULT = 1;
pub const HTTRANSPARENT: LRESULT = -1;
pub const HTRANSPARENT_CURSOR_OK: LRESULT = 1;

pub const SW_SHOWNA: i32 = 8;
pub const SW_HIDE: i32 = 0;
pub const SW_SHOW: i32 = 5;
pub const SWP_NOSIZE: UINT = 0x0001;
pub const SWP_NOMOVE: UINT = 0x0002;
pub const SWP_NOACTIVATE: UINT = 0x0010;
pub const SWP_NOZORDER: UINT = 0x0004;
pub const SWP_NOREDRAW: UINT = 0x0008;
pub const SWP_NOOWNERZORDER: UINT = 0x0200;
/// HWND_TOPMOST / HWND_NOTOPMOST are sentinel window handles, not pointers.
pub const HWND_TOPMOST: HWND = -1isize as *mut c_void;
pub const HWND_NOTOPMOST: HWND = -2isize as *mut c_void;

pub const PM_REMOVE: UINT = 0x0001;
pub const PM_NOREMOVE: UINT = 0x0000;
pub const GWLP_USERDATA: LONG = -21;
pub const GCW_ATOM: LONG = -32;

pub const SM_CXSCREEN: i32 = 0;
pub const SM_CYSCREEN: i32 = 1;
pub const SM_CMONITORS: i32 = 80;
pub const SM_XVIRTUALSCREEN: i32 = 76;
pub const SM_YVIRTUALSCREEN: i32 = 77;
pub const SM_CXVIRTUALSCREEN: i32 = 78;
pub const SM_CYVIRTUALSCREEN: i32 = 79;
pub const IDC_ARROW: *const WCHAR = 32512 as *const WCHAR;
pub const IDC_SIZEALL: *const WCHAR = 32646 as *const WCHAR;
pub const IDI_APPLICATION: *const WCHAR = 32512 as *const WCHAR;

pub const SPI_GETWORKAREA: UINT = 0x0030;
pub const MONITOR_DEFAULTTONEAREST: DWORD = 2;
pub const MONITORINFOF_PRIMARY: DWORD = 1;

// ---------------------------------------------------------------------------------------------
// layered windows
// ---------------------------------------------------------------------------------------------
pub const ULW_ALPHA: DWORD = 2;
pub const ULW_COLORKEY: DWORD = 1;
pub const ULW_OPAQUE: DWORD = 4;
pub const ULW_EX_NORESIZE: DWORD = 8;

/// `UpdateLayeredWindowIndirect`'s parameter block. The *only* way to present a dirty rect on a
/// layered window: `UpdateLayeredWindow` itself takes no update rectangle, so the sub-rect present
/// that keeps a settled clock cheap goes through this struct.
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct UPDATELAYEREDWINDOWINFO {
    pub cb_size: DWORD,
    pub pt_dst: *const POINT,
    pub psize: *const SIZE,
    pub hdc_src: HDC,
    pub pt_src: *const POINT,
    pub pblend: *const BLENDFUNCTION,
    pub pv_source_transform: *const c_void,
    pub cr_key: COLORREF,
    pub dw_flags: DWORD,
    pub prc_dirty: *const WINRECT,
}
const _: [(); 72] = [(); size_of::<UPDATELAYEREDWINDOWINFO>()];
pub const AC_SRC_OVER: BYTE = 0;
pub const AC_SRC_ALPHA: BYTE = 1;
pub const BI_RGB: DWORD = 0;
pub const DIB_RGB_COLORS: i32 = 0;

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct POINT {
    pub x: LONG,
    pub y: LONG,
}
const _: [(); 8] = [(); size_of::<POINT>()];

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct SIZE {
    pub cx: LONG,
    pub cy: LONG,
}
const _: [(); 8] = [(); size_of::<SIZE>()];

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct WINRECT {
    pub left: LONG,
    pub top: LONG,
    pub right: LONG,
    pub bottom: LONG,
}
const _: [(); 16] = [(); size_of::<WINRECT>()];

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct MSG {
    pub hwnd: HWND,
    pub message: UINT,
    pub wparam: WPARAM,
    pub lparam: LPARAM,
    pub time: DWORD,
    pub pt: POINT,
}
const _: [(); 48] = [(); size_of::<MSG>()];

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct BLENDFUNCTION {
    pub blend_op: BYTE,
    pub blend_flags: BYTE,
    pub source_constant_alpha: BYTE,
    pub alpha_format: BYTE,
}
const _: [(); 4] = [(); size_of::<BLENDFUNCTION>()];

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct BITMAPINFOHEADER {
    pub bi_size: DWORD,
    pub bi_width: LONG,
    /// Negative means top-down, which is what the painter's row order already is.
    pub bi_height: LONG,
    pub bi_planes: WORD,
    pub bi_bit_count: WORD,
    pub bi_compression: DWORD,
    pub bi_size_image: DWORD,
    pub bi_x_pels_per_meter: LONG,
    pub bi_y_pels_per_meter: LONG,
    pub bi_clr_used: DWORD,
    pub bi_clr_important: DWORD,
}
const _: [(); 40] = [(); size_of::<BITMAPINFOHEADER>()];

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct RGBQUAD {
    pub rgb_blue: BYTE,
    pub rgb_green: BYTE,
    pub rgb_red: BYTE,
    pub rgb_reserved: BYTE,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct BITMAPINFO {
    pub header: BITMAPINFOHEADER,
    pub colors: [RGBQUAD; 1],
}
const _: [(); 44] = [(); size_of::<BITMAPINFO>()];

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct WNDCLASSEXW {
    pub cb_size: UINT,
    pub style: UINT,
    pub lpfn_wnd_proc: Option<FN_WNDPROC>,
    pub cb_cls_extra: LONG,
    pub cb_wnd_extra: LONG,
    pub h_instance: HMODULE,
    pub h_icon: HICON,
    pub h_cursor: HCURSOR,
    pub h_br_background: HBRUSH,
    pub lpsz_menu_name: *const WCHAR,
    pub lpsz_class_name: *const WCHAR,
    pub h_icon_sm: HICON,
}
const _: [(); 80] = [(); size_of::<WNDCLASSEXW>()];

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct MONITORINFO {
    pub cb_size: DWORD,
    pub rc_monitor: WINRECT,
    pub rc_work: WINRECT,
    pub dw_flags: DWORD,
}
const _: [(); 40] = [(); size_of::<MONITORINFO>()];

/// The taskbar's edge and state, for `ABM_GETTASKBARPOS` / `ABM_GETSTATE`.
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct APPBARDATA {
    pub cb_size: UINT,
    pub hwnd: HWND,
    pub callback_message: UINT,
    pub edge: UINT,
    pub rc: WINRECT,
    pub l_param: LONG_PTR,
}
const _: [(); 56] = [(); size_of::<APPBARDATA>()];
pub const ABM_GETTASKBARPOS: DWORD = 0x0005;
pub const ABM_GETSTATE: DWORD = 0x0004;
pub const ABS_AUTOHIDE: DWORD = 0x0001;
pub const ABE_LEFT: UINT = 0;
pub const ABE_TOP: UINT = 1;
pub const ABE_RIGHT: UINT = 2;
pub const ABE_BOTTOM: UINT = 3;

/// `NOTIFYICONDATAW`, exactly as the SDK declares it. `cb_size` is set from `size_of` at the call
/// site, so a layout mistake here shows up as a tray icon that refuses to appear on the first run
/// in development, not as a buffer overrun on a user's machine.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct NOTIFYICONDATAW {
    pub cb_size: DWORD,
    pub hwnd: HWND,
    pub uid: UINT,
    pub flags: UINT,
    pub callback_message: UINT,
    pub icon: HICON,
    pub x: LONG,
    pub y: LONG,
    pub timeout: UINT,
    pub tip: [WCHAR; 128],
    pub state: DWORD,
    pub state_mask: DWORD,
    pub info: [WCHAR; 256],
    pub version_or_timeout: DWORD,
    pub info_title: [WCHAR; 64],
    pub info_flags: DWORD,
    pub guid_item: [u8; 16],
    pub balloon_icon: HICON,
}
const _: [(); 992] = [(); size_of::<NOTIFYICONDATAW>()];

pub const NIM_ADD: DWORD = 0x0000;
pub const NIM_MODIFY: DWORD = 0x0001;
pub const NIM_DELETE: DWORD = 0x0002;
pub const NIM_SETVERSION: DWORD = 0x0004;
pub const NIF_MESSAGE: UINT = 0x0001;
pub const NIF_ICON: UINT = 0x0002;
pub const NIF_TIP: UINT = 0x0004;
pub const NIF_STATE: UINT = 0x0008;
pub const NIF_INFO: UINT = 0x0010;
pub const NIS_HIDDEN: DWORD = 0x0001;
pub const NIS_SHAREDICON: DWORD = 0x0002;
pub const NOTIFYICON_VERSION_4: DWORD = 4;
/// Low word of `lParam` for `WM_TRAYICON`.
pub const NIN_SELECT: UINT = WM_USER + 0;
pub const NINF_KEY: UINT = 0x1;
pub const WM_CONTEXTMENU_L: UINT = 0x007B;

pub const MF_STRING: DWORD = 0x0000;
pub const MF_SEPARATOR: DWORD = 0x0800;
pub const MF_CHECKED: DWORD = 0x0008;
pub const MF_UNCHECKED: DWORD = 0x0000;
pub const MF_DISABLED: DWORD = 0x0002;
pub const MF_GRAYED: DWORD = 0x0001;
pub const TPM_RETURNCMD: DWORD = 0x0100;
pub const TPM_LEFTALIGN: DWORD = 0x0000;
pub const TPM_RIGHTBUTTON: DWORD = 0x0002;
pub const TPM_BOTTOMALIGN: DWORD = 0x0020;
pub const TPM_NONOTIFY: DWORD = 0x0080;

pub const WM_LBUTTONDBLCLK_TRAY: UINT = WM_LBUTTONDBLCLK;
pub const RDW_INVALIDATE: UINT = 0x0001;

/// `DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2`, a sentinel pseudo-handle.
pub const DPI_AWARENESS_CONTEXT_PM_V2: HANDLE = -4isize as *mut c_void;
pub const LOGPIXELSX: i32 = 88;
pub const LOGPIXELSY: i32 = 90;

// ---------------------------------------------------------------------------------------------
// imports
// ---------------------------------------------------------------------------------------------
#[link(name = "user32")]
extern "system" {
    pub fn RegisterClassExW(class: *const WNDCLASSEXW) -> WORD;
    pub fn CreateWindowExW(
        ex_style: DWORD,
        class_name: *const WCHAR,
        window_name: *const WCHAR,
        style: DWORD,
        x: LONG,
        y: LONG,
        w: LONG,
        h: LONG,
        parent: HWND,
        menu: HMENU,
        instance: HMODULE,
        param: *const c_void,
    ) -> HWND;
    pub fn DefWindowProcW(hwnd: HWND, msg: UINT, w: WPARAM, l: LPARAM) -> LRESULT;
    pub fn DestroyWindow(hwnd: HWND) -> BOOL;
    pub fn ShowWindow(hwnd: HWND, cmd: i32) -> BOOL;
    pub fn UpdateWindow(hwnd: HWND) -> BOOL;
    pub fn SetWindowPos(
        hwnd: HWND,
        after: HWND,
        x: LONG,
        y: LONG,
        w: LONG,
        h: LONG,
        flags: UINT,
    ) -> BOOL;
    pub fn GetWindowRect(hwnd: HWND, rect: *mut WINRECT) -> BOOL;
    pub fn GetMessageW(msg: *mut MSG, hwnd: HWND, first: UINT, last: UINT) -> BOOL;
    pub fn PeekMessageW(msg: *mut MSG, hwnd: HWND, first: UINT, last: UINT, flags: UINT) -> BOOL;
    pub fn TranslateMessage(msg: *const MSG) -> BOOL;
    pub fn DispatchMessageW(msg: *const MSG) -> LRESULT;
    pub fn PostQuitMessage(code: i32);
    pub fn PostMessageW(hwnd: HWND, msg: UINT, w: WPARAM, l: LPARAM) -> BOOL;
    pub fn SendMessageW(hwnd: HWND, msg: UINT, w: WPARAM, l: LPARAM) -> LRESULT;
    pub fn SetTimer(hwnd: HWND, id: UINT_PTR, elapsed: UINT, cb: Option<unsafe extern "system" fn(HWND, UINT, UINT_PTR, DWORD)>) -> UINT_PTR;
    pub fn KillTimer(hwnd: HWND, id: UINT_PTR) -> BOOL;
    pub fn SetCapture(hwnd: HWND) -> HWND;
    pub fn ReleaseCapture() -> BOOL;
    pub fn GetCursorPos(point: *mut POINT) -> BOOL;
    pub fn SetCursor(cursor: HCURSOR) -> HCURSOR;
    pub fn LoadCursorW(instance: HMODULE, name: *const WCHAR) -> HCURSOR;
    pub fn GetSystemMetrics(index: i32) -> i32;
    pub fn SetProcessDPIAware() -> BOOL;
    pub fn MonitorFromWindow(hwnd: HWND, flags: DWORD) -> *mut c_void;
    pub fn MonitorFromPoint(pt: POINT, flags: DWORD) -> *mut c_void;
    pub fn GetMonitorInfoW(monitor: *mut c_void, info: *mut MONITORINFO) -> BOOL;
    pub fn SystemParametersInfoW(action: UINT, param: UINT, value: *mut c_void, flags: UINT) -> BOOL;
    pub fn CreateIcon(
        instance: HMODULE,
        w: i32,
        h: i32,
        planes: BYTE,
        bit_count: BYTE,
        and_mask: *const BYTE,
        xor_mask: *const BYTE,
    ) -> HICON;
    pub fn DestroyIcon(icon: HICON) -> BOOL;
    pub fn CreatePopupMenu() -> HMENU;
    pub fn AppendMenuW(menu: HMENU, flags: UINT, id: UINT_PTR, text: *const WCHAR) -> BOOL;
    pub fn TrackPopupMenuEx(menu: HMENU, flags: UINT, x: i32, y: i32, hwnd: HWND, tpm: *const c_void) -> UINT;
    pub fn DestroyMenu(menu: HMENU) -> BOOL;
    pub fn CheckMenuItem(menu: HMENU, id: UINT_PTR, flags: UINT) -> UINT;
    pub fn EnableMenuItem(menu: HMENU, id: UINT_PTR, flags: UINT) -> BOOL;
    pub fn SetForegroundWindow(hwnd: HWND) -> BOOL;
    pub fn GetForegroundWindow() -> HWND;
    pub fn GetAncestor(hwnd: HWND, flags: UINT) -> HWND;
    pub fn SetWindowLongPtrW(hwnd: HWND, index: LONG, value: LONG_PTR) -> LONG_PTR;
    pub fn GetWindowLongPtrW(hwnd: HWND, index: LONG) -> LONG_PTR;
    pub fn UpdateLayeredWindow(
        hwnd: HWND,
        dc_dest: HDC,
        pt_pos: *const POINT,
        size: *const SIZE,
        dc_src: HDC,
        pt_src: *const POINT,
        key: COLORREF,
        blend: *const BLENDFUNCTION,
        flags: DWORD,
    ) -> BOOL;
    pub fn UpdateLayeredWindowIndirect(hwnd: HWND, info: *const UPDATELAYEREDWINDOWINFO) -> BOOL;
    pub fn GetDpiForWindow(hwnd: HWND) -> UINT;
    pub fn SetProcessDpiAwarenessContext(ctx: HANDLE) -> BOOL;
    pub fn IsWindow(hwnd: HWND) -> BOOL;
    pub fn ScreenToClient(hwnd: HWND, point: *mut POINT) -> BOOL;
}

pub type COLORREF = DWORD;

#[link(name = "gdi32")]
extern "system" {
    pub fn GetDC(hwnd: HWND) -> HDC;
    pub fn ReleaseDC(hwnd: HWND, dc: HDC) -> i32;
    pub fn CreateCompatibleDC(dc: HDC) -> HDC;
    pub fn CreateCompatibleBitmap(dc: HDC, w: i32, h: i32) -> HBITMAP;
    pub fn CreateDIBSection(
        dc: HDC,
        info: *const BITMAPINFO,
        usage: u32,
        bits: *mut *mut c_void,
        section: HANDLE,
        offset: UINT,
    ) -> HBITMAP;
    pub fn SelectObject(dc: HDC, obj: *mut c_void) -> *mut c_void;
    pub fn DeleteObject(obj: *mut c_void) -> BOOL;
    pub fn DeleteDC(dc: HDC) -> BOOL;
    pub fn GetDeviceCaps(dc: HDC, index: i32) -> i32;
}

#[link(name = "kernel32")]
extern "system" {
    pub fn GetModuleHandleW(name: *const WCHAR) -> HMODULE;
    pub fn GetLastError() -> DWORD;
    pub fn CreateMutexW(attrs: *const c_void, initial_owner: BOOL, name: *const WCHAR) -> HANDLE;
    pub fn CloseHandle(obj: HANDLE) -> BOOL;
    pub fn GetProcAddress(module: HMODULE, name: *const i8) -> *const c_void;
    pub fn QueryPerformanceCounter(count: *mut i64) -> BOOL;
    pub fn QueryPerformanceFrequency(freq: *mut i64) -> BOOL;
    pub fn GetLocalTime(sys: *mut SYSTEMTIME);
    pub fn GetSystemTimeAsFileTime(ft: *mut FILETIME);
    pub fn GetTimeZoneInformation(info: *mut TIME_ZONE_INFORMATION) -> DWORD;
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct SYSTEMTIME {
    pub year: WORD,
    pub month: WORD,
    pub day_of_week: WORD,
    pub day: WORD,
    pub hour: WORD,
    pub minute: WORD,
    pub second: WORD,
    pub milliseconds: WORD,
}
const _: [(); 16] = [(); size_of::<SYSTEMTIME>()];

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FILETIME {
    pub low: DWORD,
    pub high: DWORD,
}
const _: [(); 8] = [(); size_of::<FILETIME>()];

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct TIME_ZONE_INFORMATION {
    pub bias: LONG,
    pub standard_name: [WCHAR; 32],
    pub standard_date: SYSTEMTIME,
    pub standard_bias: LONG,
    pub daylight_name: [WCHAR; 32],
    pub daylight_date: SYSTEMTIME,
    pub daylight_bias: LONG,
}
const _: [(); 172] = [(); size_of::<TIME_ZONE_INFORMATION>()];

#[link(name = "shell32")]
extern "system" {
    pub fn Shell_NotifyIconW(message: DWORD, data: *const NOTIFYICONDATAW) -> BOOL;
}

#[link(name = "winmm")]
extern "system" {
    pub fn timeBeginPeriod(period: UINT) -> UINT;
    pub fn timeEndPeriod(period: UINT) -> UINT;
}

// ---------------------------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------------------------

/// UTF-16 with a trailing NUL, for the handful of `*const WCHAR` arguments. A fixed buffer rather
/// than an allocation: the only strings handed to the API here are a class name, a title and a
/// tooltip, all bounded and all created once.
#[must_use]
pub fn wide(s: &str) -> Vec<WCHAR> {
    let mut v: Vec<WCHAR> = s.encode_utf16().collect();
    v.push(0);
    v
}

/// `ERROR_ALREADY_EXISTS`, the only `GetLastError` value the startup path reads.
pub const ERROR_ALREADY_EXISTS: DWORD = 183;
pub const ERROR_PROC_NOT_FOUND: DWORD = 127;

#[must_use]
pub fn last_error() -> DWORD {
    unsafe { GetLastError() }
}

/// Last-resort DPI: `GetDpiForWindow` is Win10 1607+, so it is resolved at runtime and the fallback
/// is the old system-wide value read off a screen DC.
#[must_use]
pub fn dpi_of_window(hwnd: HWND) -> UINT {
    unsafe {
        // The symbol is imported normally here, and Windows 10 1607 is the documented floor for the
        // whole app (see README), so no dynamic resolution is needed. If the floor ever moves back
        // to Windows 8, this is the one call that must become a GetProcAddress lookup.
        let d = GetDpiForWindow(hwnd);
        if d != 0 {
            return d;
        }
        let dc = GetDC(std::ptr::null_mut());
        let x = GetDeviceCaps(dc, LOGPIXELSX);
        let y = GetDeviceCaps(dc, LOGPIXELSY);
        ReleaseDC(std::ptr::null_mut(), dc);
        if x > 0 && x == y {
            x as UINT
        } else {
            96
        }
    }
}

/// Ask the process to be Per-Monitor V2 aware. On builds without the export the call is skipped and
/// the app still works, just without per-monitor rescaling — which is why this is looked up by name
/// instead of imported.
///
/// # Safety
///
/// Calls a Win32 entry point; the pointer returned by `GetProcAddress` is cast to the function's
/// type, which is only sound if the name resolves to that API. It does.
pub unsafe fn apply_dpi_awareness() -> bool {
    let module = GetModuleHandleW(wide("user32.dll").as_ptr());
    if module.is_null() {
        return false;
    }
    let name = b"SetProcessDpiAwarenessContext\0";
    let addr = GetProcAddress(module, name.as_ptr() as *const i8);
    if addr.is_null() {
        // Pre-1703: the best available is system-DPI aware, which is still better than nothing.
        SetProcessDPIAware();
        return false;
    }
    type Fn = unsafe extern "system" fn(HANDLE) -> BOOL;
    let f: Fn = std::mem::transmute::<*const c_void, Fn>(addr);
    f(DPI_AWARENESS_CONTEXT_PM_V2) != 0
}

/// `SHAppBarMessage` is in `shell32` but the answers are advisory (which edge the taskbar is on),
/// so a failure is simply "no taskbar information", not an error.
#[must_use]
pub fn query_taskbar(hwnd: HWND) -> Option<(bool, bool)> {
    unsafe {
        let module = GetModuleHandleW(wide("shell32.dll").as_ptr());
        if module.is_null() {
            return None;
        }
        let name = b"SHAppBarMessage\0";
        let addr = GetProcAddress(module, name.as_ptr() as *const i8);
        if addr.is_null() {
            return None;
        }
        type Fn = unsafe extern "system" fn(DWORD, *mut APPBARDATA) -> ULONG;
        let f: Fn = std::mem::transmute::<*const c_void, Fn>(addr);
        let mut state = APPBARDATA { cb_size: size_of::<APPBARDATA>() as UINT, hwnd, ..Default::default() };
        let state_ok = f(ABM_GETSTATE, &mut state) != 0;
        let auto_hide = state_ok && (state.l_param as DWORD & ABS_AUTOHIDE) != 0;
        let mut pos = APPBARDATA { cb_size: size_of::<APPBARDATA>() as UINT, hwnd, ..Default::default() };
        if f(ABM_GETTASKBARPOS, &mut pos) == 0 {
            return Some((false, auto_hide));
        }
        Some((pos.edge == ABE_TOP, auto_hide))
    }
}
